### ISSUE TITLE
Error: Expected a Number but got a Buffer - RedDot@0.3

### ISSUE THREAD

**Issue by gbsix** [Autumn-one/RedDot#2]
QQ聊天窗口按ESC键退出的时候出现错误弹窗如下图，如果点击右上角的X关闭则没有错误弹窗。
![image](https://github.com/user-attachments/assets/9fa30a58-e92f-4bdf-b765-6ba508c3e2a5)

**Comment by Autumn-one** [comment]
问题是必现还是偶现？

**Comment by Autumn-one** [comment]
下个版本会解决这个问题

**Comment by Autumn-one** [comment]
- [ ]
