### ISSUE TITLE
VSCODE 终端和编辑器小红点都无法正常切换

### ISSUE THREAD

**Issue by shenghansen** [Autumn-one/RedDot#4]
在vscode的终端和编辑器，小红点永远是红色的，可以显示大小写切换，但是无法显示中英文切换，而且鼠标变成输入样式，鼠标回退也无法指示
![image](https://github.com/user-attachments/assets/b136cdc7-1d8c-40b6-9c7e-0875b234bbbf)
![image](https://github.com/user-attachments/assets/a7370b94-df24-41f7-bcfc-0b4249f2a45d)

**Comment by Autumn-one** [comment]
是什么输入法？

**Comment by shenghansen** [comment]
微软自带输入法

**Comment by Liu0345** [comment]
我也测试到了这个现象，使用的是 搜狗输入法

**Comment by Autumn-one** [comment]
> 微软自带输入法

微软输入法用输入法模式二，设置里有

**Comment by Autumn-one** [comment]
> 我也测试到了这个现象，使用的是 搜狗输入法

确定是最新版本，这个我无法复现

**Comment by Liu0345** [comment]
> > 我也测试到了这个现象，使用的是 搜狗输入法
> 
> 确定是最新版本，这个我无法复现

使用的是最新的 [RedDot@0.5](https://github.com/Autumn-one/RedDot/releases/tag/v0.5)

**Comment by Autumn-one** [comment]
> > > 我也测试到了这个现象，使用的是 搜狗输入法
> > 
> > 
> > 确定是最新版本，这个我无法复现
> 
> 使用的是最新的 [RedDot@0.5](https://github.com/Autumn-one/RedDot/releases/tag/v0.5)， 嗷，我是跨屏幕了！

夸屏幕与中英文识别没关系，如果你设置没问题，我能想到的也只有权限问题了

**Comment by Liu0345** [comment]
其他的及时通讯软件（微信、QQ），酷狗、PDF都是正常的

下图是屏幕的分配
![image](https://github.com/user-attachments/assets/1e3e0f26-c1af-49b4-b3a5-1a6577f7ab68)

**Comment by shenghansen** [comment]
使用输入法模式二后正常了，我应该是之前测试的时候修改配置没有点确定
