### ISSUE TITLE
[功能建议] 应用常用输入模式/鼠标活动时 不提示；编程场景智能切换

### ISSUE THREAD

**Issue by photkey** [Autumn-one/RedDot#7]
## 1. App常用输入模式 不提示

根据不同应用的常用输入模式，可设置指定应用 仅在切换到非常用状态时才显示提示，这样可以减少提示对视觉的干扰，在非常用输入模式下 又能及时提醒。

### 具体场景示例

- 中文常用应用（如微信、QQ、记事本等）
  - 中文状态：不显示提示
  - 英文/大写状态：显示提示
- 英文常用应用（如CMD、VSCode、Xshell等）
  - 英文状态：不显示提示
  - 中文/大写状态：显示提示

本来我想需要增加一个设置项，可以指定每一个应用 对应的常用输入状态；后来一想不用这么麻烦，不需要修改配置，利用现有设置的默认输入状态设置即可，只要添加到对应输入法里面的应用，在默认输入状态下，就不提示。

### 自动输入法切换

指定应用内 自动切换输入模式，比方如果在vscode中按下ESC键 自动切换至英文（使用vim插件）

### 写注释智能切换中文

可设置在哪些应用内（vscode/notepad……），根据当前编辑的文件名 在写注释时 自动切换中文模式，比方：

- 标题中含有`.ahk` ：`; + 空格` → 切换中文
- 标题中含有`.py`：`# + 空格` → 切换中文

需要统计一下常见编程语言的文件后缀名 跟 对应的注释符号

## 3. 鼠标交互优化

鼠标活动时（移动或点击）隐藏状态提示，理由如下：
1. 这个时候肯定不会是输入状态；
2. 此时可以通过鼠标颜色来确认状态；
3. 减少鼠标选中文字时的视觉干扰。

**Comment by Autumn-one** [comment]
2.之前写过一个用于面向这个问题的软件，但不是这个思路，而是编程的时候根据后缀只将中文标点转换成英文，关于输入法自动切换，这个如果要想做有足够的可靠性需要的工作量比较大，而且能做的功能很有限，目前不具备做这个功能的时间。
3.这本质应该可以理解为按需显示，想法没错，但实际运行的时候会导致丢失一些预先获取中英文状态的时机，我目前mac上用的一款软件做了按需显示中英文状态，我觉得感受很糟糕，的确某些场景看起来不需要知道中英文的状态，但是在将要输入的时候提前一点时间知道中英文状态对我来说会有更好的舒适性，例如我将要输入的时候手碰到了触控板导致鼠标移动或者通过鼠标点击来插入光标输入，这些都有可能丢失我预先知道中英文状态的机会（这些假设前提是关闭了鼠标本身的提示，因为有些人并不会打开这个功能），本身圆点的设计已经足够无扰化，所以在不具备更完备理由的情况下，功能不会被实现，反之如果能够给出方案并论证可以不丢失预先知道中英文状态的机会那么这个功能将有可能被实现，另一个可能性是你可能希望在鼠标提示开启的时候启用这项功能，这个可能被接受，但是其存在于代办事项的优先级将不会高。
